import type { Metadata } from "next";
import "remixicon/fonts/remixicon.css";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "./_component/navBar";
import ReduxProvider from "@/lib/store";
import {ClerkProvider} from "@clerk/nextjs"
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   <ClerkProvider afterSignOutUrl="/">
      
        <html lang="en">
          <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
              <ReduxProvider>
              <NavBar/>
              {children}
               </ReduxProvider>
          </body>
        </html>

   </ClerkProvider>
  );
}